feat: DEV-1586: Add support for new export with snapshots to SDK
heartexlabs/label-studio-sdk pull request #34
Opened 2022-02-02 09:55 UTC by KonstantinKorotaev

2022-03-02 10:58 UTC, makseq requested changes

2022-03-02 10:58 UTC, makseq commented on label_studio_sdk/project.py
> +                      serialization_options_drafts: bool = True,
@KonstantinKorotaev I would wrap serialization into a separate class with strict options. The same thing I would do for annotations_filter. Are you sure `interpolate_key_frames` is outside of `serializerion_options`?

2022-03-14 16:03 UTC, KonstantinKorotaev commented on label_studio_sdk/project.py
> +                      serialization_options_drafts: bool = True,
interpolate_key_frames  moved

2022-03-14 21:39 UTC, makseq approved these changes

2022-03-14 21:39 UTC, merged